# Generated by Django 3.1.2 on 2020-10-04 08:22

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthProvider',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('access_token_url', models.TextField()),
                ('access_token_params', models.TextField(blank=True, null=True)),
                ('authorize_url', models.TextField(blank=True, null=True)),
                ('authorize_params', models.TextField(blank=True, null=True)),
                ('api_base_url', models.TextField(blank=True, null=True)),
                ('client_kwargs', models.TextField(blank=True, null=True)),
                ('defaultScope', models.TextField(blank=True, null=True)),
                ('redirectUrl', models.TextField(blank=True, null=True)),
                ('flow', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meterstand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh_180', models.IntegerField()),
                ('kwh_181', models.IntegerField()),
                ('kwh_182', models.IntegerField()),
                ('kwh_280', models.IntegerField()),
                ('kwh_281', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('application', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('severity', models.IntegerField()),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OAuth2Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('token_type', models.CharField(max_length=40)),
                ('access_token', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True)),
                ('expires_at', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
    ]
