# Generated by Django 3.1.2 on 2020-10-04 11:53

import api.modules.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', api.modules.encrypted_fields.EncryptedTextField()),
                ('encrypted_value', api.modules.encrypted_fields.EncryptedTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token',
            field=api.modules.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='oauthprovider',
            name='client_secret',
            field=api.modules.encrypted_fields.EncryptedTextField(),
        ),
    ]
