# Generated by Django 3.1.2 on 2020-10-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201004_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='application',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='severity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
