# Generated by Django 3.1.2 on 2020-10-04 10:00

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='column1',
            field=api.fields.EncryptedTextField(),
        ),
    ]
