# Generated by Django 3.1.1 on 2020-09-28 12:17

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_meterstand_oauthprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test123',
            field=models.TextField(default='123'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
