# Generated by Django 3.1.1 on 2020-09-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200928_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='test123',
        ),
    ]
