# Generated by Django 3.1.2 on 2020-10-04 11:27

import api.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201004_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='encrypted_value',
            field=api.modules.encrypted_fields.EncryptedTextField(default='abc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token',
            field=api.modules.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='oauthprovider',
            name='client_secret',
            field=api.modules.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='column1',
            field=api.modules.encrypted_fields.EncryptedTextField(),
        ),
    ]
