# Generated by Django 3.1.2 on 2020-10-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201010_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterstand',
            name='kwh_282',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
