# Generated by Django 3.1.1 on 2020-10-01 07:21

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_oauth2token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthprovider',
            old_name='credentials',
            new_name='client_secret',
        ),
        migrations.RenameField(
            model_name='oauthprovider',
            old_name='id',
            new_name='name',
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='access_token_params',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='access_token_url',
            field=models.TextField(default='tempval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='api_base_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='authorize_params',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='authorize_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='client_id',
            field=models.TextField(default='tempval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='client_kwargs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meterstand',
            name='user',
            field=models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='user',
            field=models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oauthprovider',
            name='defaultScope',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oauthprovider',
            name='flow',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oauthprovider',
            name='redirectUrl',
            field=models.TextField(null=True),
        ),
    ]
