# Generated by Django 3.1.4 on 2020-12-22 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_oauth2state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthprovider',
            old_name='defaultScope',
            new_name='default_scope',
        ),
        migrations.RenameField(
            model_name='oauthprovider',
            old_name='redirectUrl',
            new_name='redirect_uri',
        ),
    ]
