# Generated by Django 3.1.1 on 2020-10-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201002_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='expires_at',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
