# Generated by Django 3.1.4 on 2020-12-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201222_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth2state',
            name='expires',
        ),
    ]
