# Generated by Django 3.1.4 on 2020-12-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201222_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='expires_at',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
