# Generated by Django 3.1.4 on 2020-12-23 18:13

import api.modules.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201222_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2token',
            name='password',
            field=api.modules.encrypted_fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oauth2token',
            name='username',
            field=api.modules.encrypted_fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token',
            field=api.modules.encrypted_fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
