# Generated by Django 3.1.4 on 2020-12-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201223_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthprovider',
            name='flow',
            field=models.TextField(blank=True, choices=[('password', 'password'), ('authorization_code', 'authorization_code')], null=True),
        ),
    ]
