# Generated by Django 3.2.6 on 2021-09-14 06:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('key', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[-0-9a-zA-Z ]*$', 'Only alphanumeric characters, spaces or dashes are allowed.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactoryNodeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='FactoryRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('key', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[-0-9a-zA-Z ]*$', 'Only alphanumeric characters, spaces or dashes are allowed.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('key', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[-0-9a-zA-Z ]*$', 'Only alphanumeric characters, spaces or dashes are allowed.')])),
                ('power_usage', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('key', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[-0-9a-zA-Z ]*$', 'Only alphanumeric characters, spaces or dashes are allowed.')])),
                ('type', models.CharField(choices=[('Node', 'Node'), ('Well', 'Well')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('key', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[-0-9a-zA-Z ]*$', 'Only alphanumeric characters, spaces or dashes are allowed.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('key', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[-0-9a-zA-Z ]*$', 'Only alphanumeric characters, spaces or dashes are allowed.')])),
                ('type', models.CharField(blank=True, choices=[('default', 'Default'), ('alternate', 'Alternate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='satisfactory.machinetype')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satisfactory.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satisfactory.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satisfactory.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satisfactory.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='products_input',
            field=models.ManyToManyField(related_name='products_input', through='satisfactory.RecipeInput', to='satisfactory.Product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='products_output',
            field=models.ManyToManyField(related_name='products_output', through='satisfactory.RecipeOutput', to='satisfactory.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_recipe_products', to='satisfactory.recipe'),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('key', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[-0-9a-zA-Z ]*$', 'Only alphanumeric characters, spaces or dashes are allowed.')])),
                ('purity', models.CharField(choices=[('I', 'Impure'), ('N', 'Normal'), ('P', 'Pure')], max_length=1)),
                ('miner', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satisfactory.game')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='satisfactory.nodetype')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameplayers', to='satisfactory.game')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryRecipeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recipe_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_from', to='satisfactory.factoryrecipe')),
                ('recipe_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_to', to='satisfactory.factoryrecipe')),
            ],
        ),
        migrations.AddField(
            model_name='factoryrecipe',
            name='depends_on_factoryrecipe',
            field=models.ManyToManyField(blank=True, through='satisfactory.FactoryRecipeAmount', to='satisfactory.FactoryRecipe'),
        ),
        migrations.AddField(
            model_name='factoryrecipe',
            name='depends_on_node',
            field=models.ManyToManyField(blank=True, through='satisfactory.FactoryNodeAmount', to='satisfactory.Node'),
        ),
        migrations.AddField(
            model_name='factoryrecipe',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factoryrecipes', to='satisfactory.factory'),
        ),
        migrations.AddField(
            model_name='factoryrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satisfactory.recipe'),
        ),
        migrations.AddField(
            model_name='factorynodeamount',
            name='factoryrecipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satisfactory.factoryrecipe'),
        ),
        migrations.AddField(
            model_name='factorynodeamount',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satisfactory.node'),
        ),
        migrations.AddField(
            model_name='factory',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satisfactory.game'),
        ),
    ]
